source 'http://rubygems.org'

gem 'rails', '3.0.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end

gem 'gdata_19'
#gem 'fusion_tables', '0.2.2'
gem 'nokogiri'
gem 'json'
gem 'rubyzip'
gem 'fastercsv'
gem 'pg'
gem 'capistrano'
gem 'flickraw'

group :development, :test do
  if RUBY_VERSION < '1.9'
    gem 'ruby-debug'
  else
    gem 'ruby-debug19'
  end
end

group :test do
  gem 'rspec-rails', '~> 2.0.0.beta.22'
  gem 'steak', '~> 0.4.0.beta.1'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
end
